### ISSUE TITLE
How can I do something at  all the beginning of all the requests? such as set_default_headers()

### ISSUE THREAD

**Issue by chaneyzorn** [why2pac/dp-tornado#7]
set_default_headers(self) is the original function in tornado RequestHandler.
prepare(self) do similar things.

I need those functions to set the headers to Cross-Origin Resource Sharing (CORS)

**Comment by why2pac** [comment]
You can set headers on on_prepare(self) method to apply all child requests.
Like below,

```
# /app/controller/__init__.py
class StarterController(Controller):
    def on_prepare(self):
        self.set_header('Header-Name', 'Header-Value')
```

```
# /app/controller/action.py
class ActionController(Controller):
    def get(self):
        self.finish('done')
```

If you call the path '/action', the framework will call an `on_prepare` method of StarterController and then call a `get` method of ActionController.

StarterController must be topmost controller, which is located on the root of controller path, to affect to all child requests.
Also, child controllers must not be return True or False on on_preapre method.

If you return False on on_prepare method, the framework raises an exception and showing an error response. If you return None on on_prepare method, the framework will calling a parent's on_prepare method. Or return True, the framework will not calling the parent on_prepare method.

**Comment by chaneyzorn** [comment]
It works, Thanks for your help ~
